### ISSUE TITLE
SECRET image to click is not showing up

### ISSUE THREAD

**Issue by fragoe** [lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt#2]
Firstly, I really like the idea of this project. Thanks for the effort so far. 🫶

Unfortunately, the SECRET image to click on is not showing up after encryption. I see `gpg-base-64 LS0tLS1CRUdJTiB...LS0K` but not the button.

OS: macOS Sonoma 14.4

**Comment by lajg-dev** [comment]
Hi fragoe, thank you very much for using the plugin and thank you for getting in touch about your error, I would need a little more information, since I use Mac OS Sonoma 14.4 as my base OS as well and the plugin works well for me, could you tell me if the text that you trying to encrypt, how many characters does it have? What if you are trying to encrypt more than one text at a time on the same document? And could you check that the plugin is active in the community plugins part? and any other information or screenshots you can provide me to try to replicate the error on my Mac OS Sonoma
Thank you so much!

**Comment by lajg-dev** [comment]
This issue has been unanswered for 8 days, please let me know if you still need help to resolve the problem you are experiencing. If so, please attach more information on how to replicate the issue and I will be happy to review it.

**Comment by fragoe** [comment]
Sorry for the late response.

I've checked everything and also changed themes.

- [✓] macOS Sonoma 14.4.1
- [✓] Obsidian version v1.5.12
- [✓] Community plugins are enabled 
- [✓] Theme: Default
- [✓] Text: Lorem Ipsum from https://www.lipsum.com

<img width="1108" alt="Screenshot 2024-04-29 at 20 56 23" src="https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/61689501/5df390b1-7aba-472c-ae6e-7afffaadfd05">
⤤ community plugins

<img width="931" alt="Screenshot 2024-04-29 at 21 00 59" src="https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/61689501/7328f071-6732-4e8f-90ec-d755d4e22ff2">
⤤ the original message

<img width="931" alt="Screenshot 2024-04-29 at 21 01 31" src="https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/61689501/3700b7da-bac0-4545-b40d-6bb2fc960b4d">
⤤ the command

<img width="931" alt="Screenshot 2024-04-29 at 21 01 46" src="https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/61689501/1ce0e376-e60c-49c2-a566-2a105de3314a">
⤤ in edit mode

<img width="931" alt="Screenshot 2024-04-29 at 21 01 57" src="https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/61689501/3765401e-c6cc-4df7-b169-191443413384">
⤤ in view mode, unfortunately there is no button the decrypt

**Comment by fragoe** [comment]
Encrypting the entire document leads to the same result, as you can see

<img width="933" alt="Screenshot 2024-04-29 at 21 09 57" src="https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/61689501/95eccd1a-61f3-4433-89ce-f04c3687e61e">

<img width="934" alt="Screenshot 2024-04-29 at 21 10 59" src="https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/61689501/5d77a8c3-118e-4982-b4b6-bdccdf6f1a76">

**Comment by lajg-dev** [comment]
Please let me know if now it is working for you, so I could close this ticket.

**Comment by lajg-dev** [comment]
Long wait time without response, I will close this ticket
