### ISSUE TITLE
Working on Android

### ISSUE THREAD

**Issue by Xezard** [lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt#4]
Greetings. How difficult is it to support the operation of this plugin with android devices? My notes are synced between all my devices and it is extremely sad that I cannot use encrypted notes on android.

UPD: Well, then there's another question - how realistic is it to support encryption of entire folders with all their contents?

As far as I understand from the code, a much better solution would be to use openpgp.js for universal implementation for any platform.

**Comment by lajg-dev** [comment]
It's a good idea to implement openpgp.js in this plugin, I will start working in my free time on this solution to provide support for mobile devices, I will let you know in this same issue when the release is available, thank you very much for your contribution.
